import type { Metadata } from "next";
import "../styles/globals.css";
import AppHeader from "./components/shared/AppHeader";
import AppFooter from "./components/shared/AppFooter";
import UseScrollToTop from "./hooks/useScrollToTop";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className=" bg-secondary-light dark:bg-primary-dark transition duration-300">
          <ToastContainer theme="colored" position="top-center" />
          <AppHeader />
          <div>{children}</div>
          <AppFooter />
          <UseScrollToTop />
        </div>
      </body>
    </html>
  );
}
